# Use an openjdk base image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from the local machine to the container
COPY target/my-app.jar /app/my-app.jar

# Expose the port the app will run on
EXPOSE 8081

# Run the JAR file
ENTRYPOINT ["java", "-jar", "my-app.jar"]

